local function getMethodsSafe(name)
    local ok, methods = pcall(peripheral.getMethods, name)
    return ok and methods or nil
end

local function getMethodInfoSafe(name, methodName)
    local ok, info = pcall(peripheral.getMethodInfo, name, methodName)
    return ok and info or nil
end

local function sanitizeName(str)
    local s = str:gsub("[^%w_]", "_")
    if s:match("^%d") then s = "_" .. s end
    return s
end

local function typeToClassName(ptype)
    local s = ptype:gsub("_(.)", function(c) return c:upper() end)
    s = s:gsub("^(.)", function(c) return c:upper() end)
    s = s:gsub("[^%w]", "")
    return s .. "Peripheral"
end

local function fmtType(t)
    if not t or t == "" then return "any" end
    return t
end

-- Main
local peripherals = peripheral.getNames()

if #peripherals == 0 then
    print("No peripherals found.")
    return
end

-- Group by type
local byType = {}
local typeOrder = {}

for _, name in ipairs(peripherals) do
    local ok, ptype = pcall(peripheral.getType, name)
    if ok then
        if type(ptype) == "table" then ptype = table.concat(ptype, ", ") end
        if not byType[ptype] then
            byType[ptype] = { instances = {}, methods = {} }
            table.insert(typeOrder, ptype)
        end
        local var = sanitizeName(name)
        table.insert(byType[ptype].instances, { name = name, var = var })
    end
end

-- Collect methods for each type (union across all instances)
for _, ptype in ipairs(typeOrder) do
    local data = byType[ptype]
    local seen = {}
    for _, inst in ipairs(data.instances) do
        local methods = getMethodsSafe(inst.name)
        if methods then
            for _, mname in ipairs(methods) do
                if not seen[mname] then
                    seen[mname] = true
                    data.methods[mname] = getMethodInfoSafe(inst.name, mname) or {}
                end
            end
        end
    end
end

-- Build output
local outLines = {}

-- Header
table.insert(outLines, "-- peripheral_interfaces.lua")
table.insert(outLines, "-- Auto-generated by perepherials.lua")
local typeList = {}
for _, ptype in ipairs(typeOrder) do
    table.insert(typeList, ptype)
end
table.insert(outLines, "-- Types: " .. table.concat(typeList, ", "))
table.insert(outLines, "")
table.insert(outLines, "local proxy = require(\"cc-stdlib.proxy\")")
table.insert(outLines, "")
table.insert(outLines, "local p = {}")
table.insert(outLines, "")

-- For each type: define a class with methods and create instances
for _, ptype in ipairs(typeOrder) do
    local data = byType[ptype]
    local className = typeToClassName(ptype)

    table.insert(outLines, "--[[")
    table.insert(outLines, "  Type: " .. ptype)
    for _, inst in ipairs(data.instances) do
        table.insert(outLines, "    " .. inst.name)
    end
    table.insert(outLines, "]]")
    table.insert(outLines, "")
    table.insert(outLines, "---@class " .. className)
    table.insert(outLines, "---@field _side string")
    table.insert(outLines, "---@field _type string")
    table.insert(outLines, "local " .. className .. " = {}")
    table.insert(outLines, className .. ".__index = " .. className)
    table.insert(outLines, "")

    -- Sort methods alphabetically
    local sortedMethods = {}
    for mname, _ in pairs(data.methods) do
        table.insert(sortedMethods, mname)
    end
    table.sort(sortedMethods)

    for _, mname in ipairs(sortedMethods) do
        local info = data.methods[mname]

        -- Description
        if info.description and info.description ~= "" then
            for line in info.description:gmatch("[^\n]+") do
                table.insert(outLines, "--- " .. line)
            end
        end

        -- Param annotations
        local paramNames = {}
        if info.parameters then
            for _, p in ipairs(info.parameters) do
                local pn = p.name or "arg"
                table.insert(paramNames, pn)
                table.insert(outLines, "---@param " .. pn .. " " .. fmtType(p.type))
            end
        end

        -- Return annotations
        if info.returns then
            for _, r in ipairs(info.returns) do
                local rn = r.name and (" " .. r.name) or ""
                table.insert(outLines, "---@return " .. fmtType(r.type) .. rn)
            end
        end

        -- Method signature
        local args = table.concat(paramNames, ", ")
        local callArgs = #paramNames > 0 and ", " .. table.concat(paramNames, ", ") or ""
        table.insert(outLines, "function " .. className .. ":" .. mname .. "(" .. args .. ")")
        table.insert(outLines, "    return proxy.call(self._side, \"" .. mname .. "\"" .. callArgs .. ")")
        table.insert(outLines, "end")
        table.insert(outLines, "")
    end

    -- Create instances
    for _, inst in ipairs(data.instances) do
        table.insert(outLines, "---@type " .. className)
        table.insert(outLines, "p." .. inst.var .. " = setmetatable({ _side = \"" .. inst.name .. "\", _type = \"" .. ptype .. "\" }, " .. className .. ")")
        if inst.var ~= inst.name then
            table.insert(outLines, "p[\"" .. inst.name .. "\"] = p." .. inst.var)
        end
        table.insert(outLines, "")
    end
end

table.insert(outLines, "return p")

-- Write file
local f = fs.open("peripheral_interfaces.lua", "w")
if f then
    f.write(table.concat(outLines, "\n"))
    f.close()
    print("Saved peripheral_interfaces.lua")
    print("")
    for _, ptype in ipairs(typeOrder) do
        local mcount = 0
        for _ in pairs(byType[ptype].methods) do mcount = mcount + 1 end
        print("  " .. ptype .. ": " .. mcount .. " methods, " .. #byType[ptype].instances .. " instance(s)")
    end
    local totalMethods = 0
    for _, ptype in ipairs(typeOrder) do
        for _ in pairs(byType[ptype].methods) do totalMethods = totalMethods + 1 end
    end
    print("Total: " .. totalMethods .. " methods across " .. #peripherals .. " peripheral(s)")
else
    print("Error: could not write peripheral_interfaces.lua")
end
