-- peripheral_interfaces.lua
-- Auto-generated by perepherials.lua
-- Types: gimbal_sensor, modem, altitude_sensor, navigation_table, velocity_sensor

local proxy = require("cc-stdlib.proxy")

local p = {}

--[[
  Type: gimbal_sensor
    top
]]

---@class GimbalSensorPeripheral
---@field _side string
---@field _type string
local GimbalSensorPeripheral = {}
GimbalSensorPeripheral.__index = GimbalSensorPeripheral

function GimbalSensorPeripheral:getAngles()
    return proxy.call(self._side, "getAngles")
end

function GimbalSensorPeripheral:getAnglesRad()
    return proxy.call(self._side, "getAnglesRad")
end

---@type GimbalSensorPeripheral
p.top = setmetatable({ _side = "top", _type = "gimbal_sensor" }, GimbalSensorPeripheral)

--[[
  Type: modem
    right
]]

---@class ModemPeripheral
---@field _side string
---@field _type string
local ModemPeripheral = {}
ModemPeripheral.__index = ModemPeripheral

function ModemPeripheral:callRemote()
    return proxy.call(self._side, "callRemote")
end

function ModemPeripheral:close()
    return proxy.call(self._side, "close")
end

function ModemPeripheral:closeAll()
    return proxy.call(self._side, "closeAll")
end

function ModemPeripheral:getMethodsRemote()
    return proxy.call(self._side, "getMethodsRemote")
end

function ModemPeripheral:getNameLocal()
    return proxy.call(self._side, "getNameLocal")
end

function ModemPeripheral:getNamesRemote()
    return proxy.call(self._side, "getNamesRemote")
end

function ModemPeripheral:getTypeRemote()
    return proxy.call(self._side, "getTypeRemote")
end

function ModemPeripheral:hasTypeRemote()
    return proxy.call(self._side, "hasTypeRemote")
end

function ModemPeripheral:isOpen()
    return proxy.call(self._side, "isOpen")
end

function ModemPeripheral:isPresentRemote()
    return proxy.call(self._side, "isPresentRemote")
end

function ModemPeripheral:isWireless()
    return proxy.call(self._side, "isWireless")
end

function ModemPeripheral:open()
    return proxy.call(self._side, "open")
end

function ModemPeripheral:transmit()
    return proxy.call(self._side, "transmit")
end

---@type ModemPeripheral
p.right = setmetatable({ _side = "right", _type = "modem" }, ModemPeripheral)

--[[
  Type: altitude_sensor
    altitude_sensor_0
]]

---@class AltitudeSensorPeripheral
---@field _side string
---@field _type string
local AltitudeSensorPeripheral = {}
AltitudeSensorPeripheral.__index = AltitudeSensorPeripheral

function AltitudeSensorPeripheral:getAirPressure()
    return proxy.call(self._side, "getAirPressure")
end

function AltitudeSensorPeripheral:getHeight()
    return proxy.call(self._side, "getHeight")
end

---@type AltitudeSensorPeripheral
p.altitude_sensor_0 = setmetatable({ _side = "altitude_sensor_0", _type = "altitude_sensor" }, AltitudeSensorPeripheral)

--[[
  Type: navigation_table
    navigation_table_1
]]

---@class NavigationTablePeripheral
---@field _side string
---@field _type string
local NavigationTablePeripheral = {}
NavigationTablePeripheral.__index = NavigationTablePeripheral

function NavigationTablePeripheral:getRelativeAngle()
    return proxy.call(self._side, "getRelativeAngle")
end

function NavigationTablePeripheral:getRelativeAngleRad()
    return proxy.call(self._side, "getRelativeAngleRad")
end

---@type NavigationTablePeripheral
p.navigation_table_1 = setmetatable({ _side = "navigation_table_1", _type = "navigation_table" }, NavigationTablePeripheral)

--[[
  Type: velocity_sensor
    velocity_sensor_3
    velocity_sensor_2
    velocity_sensor_1
]]

---@class VelocitySensorPeripheral
---@field _side string
---@field _type string
local VelocitySensorPeripheral = {}
VelocitySensorPeripheral.__index = VelocitySensorPeripheral

function VelocitySensorPeripheral:getVelocity()
    return proxy.call(self._side, "getVelocity")
end

---@type VelocitySensorPeripheral
p.velocity_sensor_3 = setmetatable({ _side = "velocity_sensor_3", _type = "velocity_sensor" }, VelocitySensorPeripheral)

---@type VelocitySensorPeripheral
p.velocity_sensor_2 = setmetatable({ _side = "velocity_sensor_2", _type = "velocity_sensor" }, VelocitySensorPeripheral)

---@type VelocitySensorPeripheral
p.velocity_sensor_1 = setmetatable({ _side = "velocity_sensor_1", _type = "velocity_sensor" }, VelocitySensorPeripheral)

return p